# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bl3auto < Formula
  desc "Borderlands and Wonderlands Bulk Code Redemption System"
  homepage "https://github.com/jauderho/bl3auto/"
  version "2.2.18"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/jauderho/bl3auto/releases/download/v2.2.18/bl3auto-2.2.18-macos-arm64.tar.gz"
      sha256 "a777db54a6253ae35685df88c5c125ca71b196533490fc82e245b1beb149c651"

      def install
        bin.install "bl3auto"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jauderho/bl3auto/releases/download/v2.2.18/bl3auto-2.2.18-linux-arm64.tar.gz"
      sha256 "3f5e09761df3642547556214bb8e0b3b17449011eb9db90d7e923e253f655b65"

      def install
        bin.install "bl3auto"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/jauderho/bl3auto/releases/download/v2.2.18/bl3auto-2.2.18-linux-armv6.tar.gz"
      sha256 "1fb857fea528c67442c7729f22ad9e6d8a7ebd9884b61c1cf238586a2b71fadd"

      def install
        bin.install "bl3auto"
      end
    end
  end
end
