# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bl3auto < Formula
  desc "Borderlands and Wonderlands Bulk SHiFT Code Redemption System"
  homepage "https://github.com/jauderho/bl3auto/"
  version "2.2.23"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/jauderho/bl3auto/releases/download/v2.2.23/bl3auto-2.2.23-macos-arm64.tar.gz"
      sha256 "07d194fda8d2f6ea3f37eee872a7a3312a876c43b9b95661ab23d8d6dbeaf21f"

      def install
        bin.install "bl3auto"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/jauderho/bl3auto/releases/download/v2.2.23/bl3auto-2.2.23-linux-armv6.tar.gz"
      sha256 "16b099534002d5405024225a6e519d6ac3808309ab57dbc8fed3d97cb97fcde7"

      def install
        bin.install "bl3auto"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jauderho/bl3auto/releases/download/v2.2.23/bl3auto-2.2.23-linux-arm64.tar.gz"
      sha256 "4d6d202f0821642e83018b3d9ae0569db7240d43cb6e21b06a218d8d6f5d35b2"

      def install
        bin.install "bl3auto"
      end
    end
  end
end
