# This file was generated by GoReleaser. DO NOT EDIT.
cask "bl3auto" do
  version "2.3.2"

  on_macos do
    on_intel do
      sha256 "83b0efebbf71ddedb486d2249882ee012aceef0971b315c52d19abfa25e04228"
      url "https://github.com/jauderho/bl3auto/releases/download/v#{version}/bl3auto_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "675c03e51bf735f99a17c29872460126a3aa4938fadcdf86c37017606a1c10b8"
      url "https://github.com/jauderho/bl3auto/releases/download/v#{version}/bl3auto_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "57a020ad48019273c766008edacb6b1b9d429ac489f4e6f6f2b006b3a11e3e75"
      url "https://github.com/jauderho/bl3auto/releases/download/v#{version}/bl3auto_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "94ee31748d3d25d3e31dde178794445748a8d4db4e31c6ef90ed55b5581fc966"
      url "https://github.com/jauderho/bl3auto/releases/download/v#{version}/bl3auto_#{version}_linux_arm64.tar.gz"
    end
  end

  name "bl3auto"
  desc "Borderlands and Wonderlands Bulk SHiFT Code Redemption System"
  homepage "https://github.com/jauderho/bl3auto/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bl3auto"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bl3auto"]
    end
  end

  # No zap stanza required

end
