# This file was generated by GoReleaser. DO NOT EDIT.
cask "bl3auto" do
  version "2.3.5"

  on_macos do
    on_intel do
      sha256 "72b3cf50d26f3e8f6a525f913611f910b4bdfc765e81eae0b818c0205669e4c5"
      url "https://github.com/jauderho/bl3auto/releases/download/v#{version}/bl3auto_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "1b712f896d2931ee058383d9fd23b196b1aeba3c87b1e797238ba3edfbbd9dfd"
      url "https://github.com/jauderho/bl3auto/releases/download/v#{version}/bl3auto_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "689aed973fadf295323c638afe1b2454b0ed7d042364058db94dd9a103e5c18d"
      url "https://github.com/jauderho/bl3auto/releases/download/v#{version}/bl3auto_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "2f5f95580aef2dc4acc76dc48fae90bac74e2b49288c17778e16d57098ff1677"
      url "https://github.com/jauderho/bl3auto/releases/download/v#{version}/bl3auto_#{version}_linux_arm64.tar.gz"
    end
  end

  name "bl3auto"
  desc "Borderlands and Wonderlands Bulk SHiFT Code Redemption System"
  homepage "https://github.com/jauderho/bl3auto/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bl3auto"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bl3auto"]
    end
  end

  # No zap stanza required

end
